### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'interactions.api.models'

### ISSUE THREAD

**Issue by LOLYAYDEV** [Pilot1782/bad_copeheimer#170]
### What happened?

I am getting this error when im trying to rum monobot.pyw :

ModuleNotFoundError: No module named 'interactions.api.models'

Im running it on kali linux on a virtualbox VM

I need tocheck the dev builds to prosceed but I DIDNT USE ANY DEV BUILd
i need to check it so i can click on submit new issue

### Operating Sys

Linux

### Branch

- [ ] Tried `dev-builds`

### Relevant log output

```shell
┌──(kali㉿kali)-[~/Desktop/bad_copenheimer-2.1]
└─$ python mongoBot.pyw                               
Traceback (most recent call last):
  File "/home/kali/Desktop/bad_copenheimer-2.1/mongoBot.pyw", line 14, in <module>
    from interactions.api.models import Message
ModuleNotFoundError: No module named 'interactions.api.models'
```

**Comment by Pilot1782** [comment]
This repo is depreciated, please migrate to the new one here: https://github.com/MCServerScout/Discord-Bot
