### ISSUE TITLE
Doesn't work for some reason

### ISSUE THREAD

**Issue by Z1xus** [Pilot1782/bad_copeheimer#2]
Tried to start on windows 10 with python 3.10
> C:\Users\Z1xus\Desktop\bad_copeheimer-1.2>python dis-bot.pyw
>   File "C:\Users\Z1xus\Desktop\bad_copeheimer-1.2\dis-bot.pyw", line 11
>     lower_ip_bound = 172.0.0.0 #Lowest is 10.0.0.0
>                      ^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> 
> C:\Users\Z1xus\Desktop\bad_copeheimer-1.2>

**Comment by Z1xus** [comment]
reinstalled python and all the modules. added quotes to ip bound variables, now it gives me another error

> C:\Users\Z1xus\Desktop\bad_copeheimer-1.2>python dis-bot.pyw
> testing4#9435 has connected to Discord!
> MC ping started
> Testing
> Ignoring exception in on_message
> Traceback (most recent call last):
>   File "C:\Python\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
>     await coro(*args, **kwargs)
>   File "C:\Users\Z1xus\Desktop\bad_copeheimer-1.2\dis-bot.pyw", line 48, in on_message
>     server = MC("172.65.238.212",True,255,timeout)
>   File "C:\Users\Z1xus\Desktop\bad_copeheimer-1.2\dis-bot.pyw", line 27, in MC
>     ptime()
> NameError: name 'ptime' is not defined
>

**Comment by Pilot1782** [comment]
I fixed this in the new version, the ip was not a string.
