### ISSUE TITLE
doesnt work 

### ISSUE THREAD

**Issue by TheHolyTachanka** [Pilot1782/bad_copeheimer#3]
i have these packages 
requests
2.26.0
discord
1.7.3
mcstatus
6.5.0
and i get the following error
Year 2021
MC ping started
Testing
Year 2021
Scanning 172.65.238.212 outputting True
Ignoring exception in on_message
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "dis-bot.pyw", line 73, in on_message
    status = server.status()
AttributeError: 'NoneType' object has no attribute 'status'
and yes i put my bot token
BTW thx you for making this

**Comment by Pilot1782** [comment]
Can you send the first 17 lines, (up to the path = r"qubo.jar" and replace your key with &&&&.

For example:
from requests import get
import discord
from dotenv import load_dotenv
from discord.ext import commands
import time
import os

load_dotenv()
##################################################
#Stuff for you to change
TOKEN = '&&&&&&&&&&&&&&&&&&' #Your discord bot token
lower_ip_bound = "172.0.0.0" #Lowest is 10.0.0.0
upper_ip_bound = "192.255.255.255" #Highest is 199.255.255.255
threads = 255 #Max usable is 1000
timeout = 1000 #Ping timeout in miliseconds
path = r"qubo.jar" #Path to qubo.jar
##################################################

**Comment by Pilot1782** [comment]
Also try in the shell or python terminal:
pip install python-dotenv
or:
python -m pip install python-dotenv
or:
python3 -m pip install python-dotenv

**Comment by TheHolyTachanka** [comment]
from requests import get
import discord
from dotenv import load_dotenv
from discord.ext import commands
import time
import os

load_dotenv()
##################################################
#Stuff for you to change
TOKEN = '&&&&&&&&&&&&&&&&&&' #Your discord bot token
lower_ip_bound = "172.0.0.0" #Lowest is 10.0.0.0
upper_ip_bound = "192.255.255.255" #Highest is 199.255.255.255
threads = 255 #Max usable is 1000
timeout = 1000 #Ping timeout in miliseconds
path = "C:\Users\Nikolai\Desktop\copeheimer/qubo.jar" #Path to qubo.jar
##################################################

**Comment by TheHolyTachanka** [comment]
i reinstalled the modules now i get this error sorry im new to python lol

(unicode error) 'unicodeescape' codec cant decode bytes in position 2-3:truncated zUXXXXXXXXX escape

**Comment by Pilot1782** [comment]
Ok, should be fixed in the latest version of dis-bot.pyw, try and copy the contents of the file, copy the entire file or do a fresh repo clone.

**Comment by TheHolyTachanka** [comment]
now i get invalid syntax on line 11
on the lower ip bound

**Comment by Pilot1782** [comment]
In the new new version it works.
