### ISSUE TITLE
Execution failed error.

### ISSUE THREAD

**Issue by Armoured0** [Pilot1782/bad_copeheimer#5]
I'm having problems with find and status. It seems to always come up with this error shown in pictures. I am rather new to this and any help would be much appreciated! I would like to also ask what ip bounds would be recommended as well as threads!
Thanks! 
![image](https://user-images.githubusercontent.com/48469839/142885355-b3ee834e-915b-4c62-b033-523249f03e3a.png)
![image](https://user-images.githubusercontent.com/48469839/142885435-0a8021a2-d931-483f-ade9-7e0094c0e656.png)

**Comment by Pilot1782** [comment]
In order to make the queries work properly the server needs to have enable-query=true and the proper query port specified in the status command. 

the execution failed message is a result of the query timing out

**Comment by Armoured0** [comment]
Okay let me check the config on the server!

**Comment by Armoured0** [comment]
Alright thank you very much. This fixes this issue! 👍🏼
