### ISSUE TITLE
You could probably use MCstatus to try to check if a server is whitelisted, as well as other info

### ISSUE THREAD

**Issue by BookWyrm114** [Pilot1782/bad_copeheimer#7]
MCstatus: https://github.com/Dinnerbone/mcstatus

you could try using mcstatus to get server info

**Comment by Pilot1782** [comment]
Hi I am already using McStatus with the !status command but unfortunately requesting whitelist is not possible with McStatus as it requires a login attempt which would need your personal mc account.
